server:
 port: 7003

#eureka: #单机eureka配置
#  instance:
#
#    hostname: localhost
#  client:
#    fetch-registry: false
#    register-with-eureka: false

eureka: # 多节点eureka配置
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒），为了在服务提供者断掉之后客户端刷新的时间
    enable-self-preservation: true #设置为false表示关闭保护模式（如果有些服务提供方掉线了，保护模式会让eureka重试多少次之后在删除这个提供方）
  client:
    fetch-registry: false #这一句设置自己不需要从eurake上获取注册信息
    register-with-eureka: false # 这一句和上面那一句是让eureka不把自己注册到自己上面
    service-url:
      #defaultZone: http://admin:enjoy@localhost:7001/eureka
      defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance: # eureak实例定义
    hostname: eureka3 # 定义 Eureka 实例所在的主机名称

spring:
  security:
    user:
      name: admin
      password: enjoy